apiEndpoint: https://sms86dbpe2.execute-api.eu-central-1.amazonaws.com/v1 #Use the endpoint of your api deployment here
twitchClientId: g5eg225exgjnr0cfag7oqetagdwu5y #Dev-App, you can use this if you run the app on the uri below
twitchRedirectUri: http://localhost:8080/ #The redirect uri set in your twitch app
