env:
  es6: true
  node: true
plugins:
    - require-path-exists
extends:
    - 'eslint:recommended'
    - 'plugin:require-path-exists/recommended'
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-console:
    - warn
